# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
                ('birth_date', models.DateField()),
                ('location', models.TextField(max_length=200)),
            ],
        ),
    ]
