# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
