# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20180701_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created', 'text')},
        ),
    ]
