# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20180712_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tweets.models.tweet_image_loc),
        ),
    ]
