# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20180812_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created',)},
        ),
    ]
